#pragma once

#define TIMES_TO_RUN_ALGORITHM 100

#define DEFAULT_TAB_LENGTH 1
#define INITIAL_TAB_VALUE -1

#define INITIAL_MATRIX_VALUE -1
#define DEFAULT_MATRIX_SIZE 1

#define MAX_CHARACTER_NUMBER 1000

#define DEFAULT_ENTITY_NUMBER 1

#define DEFAULT_RANDOM_MIN_VALUE 0.0
#define DEFAULT_RANDOM_MAX_VALUE 100.0

#define MINIMAL_SUPPLIER_CONTRACT_PRICE_VALUE 10.0
#define MAXIMAL_SUPPLIER_CONTRACT_PRICE_VALUE 200.0

#define MINIMAL_FACTORY_CONTRACT_PRICE_VALUE 10.0
#define MAXIMAL_FACTORY_CONTRACT_PRICE_VALUE 200.0

#define MINIMAL_WAREHOUSE_CONTRACT_PRICE_VALUE 10.0
#define MAXIMAL_WAREHOUSE_CONTRACT_PRICE_VALUE 200.0

#define MINIMAL_SELLER_CONTRACT_PRICE_VALUE 10.0
#define MAXIMAL_SELLER_CONTRACT_PRICE_VALUE 200.0

#define MINIMAL_CAPACITY_AMMOUNT 0
#define MAXIMAL_SUPPLIER_CAPACITY_AMMOUNT 400.0
#define MAXIMAL_FACTORY_CAPACITY_AMMOUNT 300.0
#define MAXIMAL_WAREHOUSE_CAPACITY_AMMOUNT 500.0
#define MAXIMAL_SELLER_CAPACITY_AMMOUNT 200.0

#define MINIMAL_CD_VALUE 0
#define MAXIMAL_CD_VALUE MAXIMAL_SUPPLIER_CAPACITY_AMMOUNT

#define MINIMAL_CF_VALUE 0
#define MAXIMAL_CF_VALUE MAXIMAL_FACTORY_CAPACITY_AMMOUNT

#define MINIMAL_CM_VALUE 0
#define MAXIMAL_CM_VALUE MAXIMAL_WAREHOUSE_CAPACITY_AMMOUNT

#define MINIMAL_XD_VALUE 0
#define MAXIMAL_XD_VALUE MAXIMAL_SUPPLIER_CAPACITY_AMMOUNT

#define MINIMAL_XF_VALUE 0
#define MAXIMAL_XF_VALUE MAXIMAL_FACTORY_CAPACITY_AMMOUNT

#define MINIMAL_XM_VALUE 20.0
#define MAXIMAL_XM_VALUE 0