#pragma once

#define TIMES_TO_RUN_ALGORITHM 1000000

#define DEFAULT_ENTITY_NUMBER 1

#define DEFAULT_TAB_LENGTH 1
#define INITIAL_TAB_VALUE -1

#define DEFAULT_MATRIX_SIZE 1
#define INITIAL_MATRIX_VALUE -1

//ammount of characters that can fit into char tab to load from file
#define MAX_CHARACTER_NUMBER 1000

//Values for Defaul Random Engine
#define DEFAULT_RANDOM_MIN_VALUE 0.0
#define DEFAULT_RANDOM_MAX_VALUE 100.0

//Contracts and Income
#define MINIMAL_SUPPLIER_CONTRACT_PRICE_VALUE 5.0
#define MAXIMAL_SUPPLIER_CONTRACT_PRICE_VALUE 30.0

#define MINIMAL_FACTORY_CONTRACT_PRICE_VALUE 5.0
#define MAXIMAL_FACTORY_CONTRACT_PRICE_VALUE 30.0

#define MINIMAL_WAREHOUSE_CONTRACT_PRICE_VALUE 5.0
#define MAXIMAL_WAREHOUSE_CONTRACT_PRICE_VALUE 30.0

#define MINIMAL_SELLER_INCOME_VALUE 50.0
#define MAXIMAL_SELLER_INCOME_VALUE 500.0

//Capacities
#define MINIMAL_CAPACITY_AMMOUNT 0.0
#define MAXIMAL_SUPPLIER_CAPACITY_AMMOUNT 100.0
#define MAXIMAL_FACTORY_CAPACITY_AMMOUNT 100.0
#define MAXIMAL_WAREHOUSE_CAPACITY_AMMOUNT 100.0
#define MAXIMAL_SELLER_CAPACITY_AMMOUNT 100.0

//DeliveryCost
#define MINIMAL_CD_VALUE 3.0
#define MAXIMAL_CD_VALUE 20.0

#define MINIMAL_CF_VALUE 3.0
#define MAXIMAL_CF_VALUE 20.0

#define MINIMAL_CM_VALUE 3.0
#define MAXIMAL_CM_VALUE 20.0

//Product Ammount Matix
#define MINIMAL_XD_VALUE 0
#define MAXIMAL_XD_VALUE 50.0

#define MINIMAL_XF_VALUE 0
#define MAXIMAL_XF_VALUE 50.0

#define MINIMAL_XM_VALUE 0.0
#define MAXIMAL_XM_VALUE 50.0