#pragma once

//FIX SOLUTION IN GETQUALITY
#define MAX_TIMES_TILL_FALLBACK 100
#define DEFAULT_SUBTRACTION_VALUE 10
//DIFF EVOLUTION INIT POPULATION TIMEOUT
#define TIMEOUT_EXEC 120.0

//CORRECT GENOTYPE TRIES
#define GENOTYPE_CORRECTION_TIMEOUT 60

//Cross Probability 
#define CROSS_PROBABILIY 0.33
#define DIFF_WEIGHT 0.4

#define TIMES_TO_RANDOM_ALGORITHM_TIMEOUT 60
#define VALIDATE_SOLUTION_TIMEOUT 60

#define DEFAULT_ENTITY_NUMBER 1

#define DEFAULT_TAB_LENGTH 1
#define INITIAL_TAB_VALUE -1

#define DEFAULT_MATRIX_SIZE 1
#define INITIAL_MATRIX_VALUE -1

//ammount of characters that can fit into char tab to load from file
#define MAX_CHARACTER_NUMBER 1000

//Values for Defaul Random Engine
#define DEFAULT_RANDOM_MIN_VALUE 0.0
#define DEFAULT_RANDOM_MAX_VALUE 100.0

//Contracts and Income
#define MINIMAL_SUPPLIER_CONTRACT_PRICE_VALUE 100
#define MAXIMAL_SUPPLIER_CONTRACT_PRICE_VALUE 1000

#define MINIMAL_FACTORY_CONTRACT_PRICE_VALUE 100
#define MAXIMAL_FACTORY_CONTRACT_PRICE_VALUE 1000

#define MINIMAL_WAREHOUSE_CONTRACT_PRICE_VALUE 100
#define MAXIMAL_WAREHOUSE_CONTRACT_PRICE_VALUE 1000

#define MINIMAL_SELLER_INCOME_VALUE 50
#define MAXIMAL_SELLER_INCOME_VALUE 500

//Capacities
#define MINIMAL_CAPACITY_AMMOUNT 1000
#define MAXIMAL_SUPPLIER_CAPACITY_AMMOUNT 7000
#define MAXIMAL_FACTORY_CAPACITY_AMMOUNT 7000
#define MAXIMAL_WAREHOUSE_CAPACITY_AMMOUNT 7000
#define MAXIMAL_SELLER_CAPACITY_AMMOUNT 7000

//DeliveryCost
#define MINIMAL_CD_VALUE 0
#define MAXIMAL_CD_VALUE 100

#define MINIMAL_CF_VALUE 0
#define MAXIMAL_CF_VALUE 100

#define MINIMAL_CM_VALUE 0
#define MAXIMAL_CM_VALUE 100

//Product Ammount Matix
#define MINIMAL_XD_VALUE 0
#define MAXIMAL_XD_VALUE 400

#define MINIMAL_XF_VALUE 0
#define MAXIMAL_XF_VALUE 300

#define MINIMAL_XM_VALUE 0.0
#define MAXIMAL_XM_VALUE 200